template = "https://github.com/giellalt/template-lang-und"
rev_id = 284
template_sha = "2037eca89479d8af6ddb6e31e662c34f302461e6"

[replacements]
__GLOTTOLOG_ID__ = "paam1238"
__LICENSE__ = "LGPL-3.0"
__REPO__ = "lang-pma"
__UND2C__ = ""
__UNDEFINED__ = "Paamese"
__UND__ = "pma"
