template = "https://github.com/giellalt/template-lang-und"
rev_id = 289
template_sha = "599009dae90448ef6fe32b71f7a6880293f3d546"

[replacements]
__GLOTTOLOG_ID__ = "paam1238"
__LICENSE__ = "LGPL-3.0"
__REPO__ = "lang-pma"
__UND2C__ = ""
__UNDEFINED__ = "Paamese"
__UND__ = "pma"
