template = "https://github.com/giellalt/template-lang-und"
rev_id = 333
template_sha = "c0f15a905d69cb451762275644bf5c3133bfc106"

[replacements]
__GLOTTOLOG_ID__ = "paam1238"
__LICENSE__ = "LGPL-3.0"
__REPO__ = "lang-pma"
__UND2C__ = ""
__UNDEFINED__ = "Paamese"
__UND__ = "pma"
